"""UTHelper Theme Presets - Configured palettes for visual options."""

THEME_PRESETS = {
    "midnight_blue": {
        "label": "Midnight Blue",
        "description": "Deep navy - mặc định",
        "bg":             "#0B0F1A",
        "surface":        "#141B2D",
        "surface_hover":  "#1A2340",
        "accent":         "#3B82F6",
        "text_primary":   "#F1F5F9",
        "text_secondary": "#94A3B8",
        "border":         "#1E293B",
        "critical": "#EF4444",
        "warning":  "#F59E0B",
        "safe":     "#10B981",
        "quiz":       "#7C3AED",
        "assignment": "#2563EB",
        "attendance": "#D97706",
        "open":       "#0891B2",
        "other":      "#6B7280",
    },
    "ocean_teal": {
        "label": "Ocean Teal",
        "description": "Calm cyan - education",
        "bg":             "#0A1628",
        "surface":        "#122035",
        "surface_hover":  "#1A2D45",
        "accent":         "#0891B2",
        "text_primary":   "#E0F2FE",
        "text_secondary": "#7DD3FC",
        "border":         "#1B3A4B",
        "critical": "#F87171",
        "warning":  "#FBBF24",
        "safe":     "#34D399",
        "quiz":       "#8B5CF6",
        "assignment": "#06B6D4",
        "attendance": "#F59E0B",
        "open":       "#22D3EE",
        "other":      "#64748B",
    },
    "sakura_pink": {
        "label": "Sakura Pink",
        "description": "Vibrant - youthful",
        "bg":             "#1A0F1C",
        "surface":        "#251828",
        "surface_hover":  "#312035",
        "accent":         "#EC4899",
        "text_primary":   "#FDF2F8",
        "text_secondary": "#F9A8D4",
        "border":         "#3B1D3F",
        "critical": "#FB7185",
        "warning":  "#FCD34D",
        "safe":     "#6EE7B7",
        "quiz":       "#A78BFA",
        "assignment": "#F472B6",
        "attendance": "#FBBF24",
        "open":       "#67E8F9",
        "other":      "#9CA3AF",
    },
    "nord_frost": {
        "label": "Nord Frost",
        "description": "Arctic - minimalist",
        "bg":             "#2E3440",
        "surface":        "#3B4252",
        "surface_hover":  "#434C5E",
        "accent":         "#88C0D0",
        "text_primary":   "#ECEFF4",
        "text_secondary": "#D8DEE9",
        "border":         "#4C566A",
        "critical": "#BF616A",
        "warning":  "#EBCB8B",
        "safe":     "#A3BE8C",
        "quiz":       "#B48EAD",
        "assignment": "#81A1C1",
        "attendance": "#D08770",
        "open":       "#8FBCBB",
        "other":      "#7B88A1",
    },
    "monokai_pro": {
        "label": "Monokai Pro",
        "description": "Warm dark - developer",
        "bg":             "#2D2A2E",
        "surface":        "#403E41",
        "surface_hover":  "#4A474B",
        "accent":         "#FFD866",
        "text_primary":   "#FCFCFA",
        "text_secondary": "#C1C0C0",
        "border":         "#5B595C",
        "critical": "#FF6188",
        "warning":  "#FFD866",
        "safe":     "#A9DC76",
        "quiz":       "#AB9DF2",
        "assignment": "#78DCE8",
        "attendance": "#FC9867",
        "open":       "#78DCE8",
        "other":      "#727072",
    },
    "solarized_dark": {
        "label": "Solarized Dark",
        "description": "Proven - readability",
        "bg":             "#002B36",
        "surface":        "#073642",
        "surface_hover":  "#0D4150",
        "accent":         "#268BD2",
        "text_primary":   "#FDF6E3",
        "text_secondary": "#93A1A1",
        "border":         "#586E75",
        "critical": "#DC322F",
        "warning":  "#B58900",
        "safe":     "#859900",
        "quiz":       "#6C71C4",
        "assignment": "#268BD2",
        "attendance": "#CB4B16",
        "open":       "#2AA198",
        "other":      "#657B83",
    },
    "steel_light": {
        "label": "Steel Light",
        "description": "Cool slate - dynamic blue",
        "mode": "light",
        "bg":             "#F8FAFC",
        "surface":        "#FFFFFF",
        "surface_hover":  "#F1F5F9",
        "accent":         "#1D4ED8",
        "text_primary":   "#0F172A",
        "text_secondary": "#475569",
        "border":         "#E2E8F0",
        "critical": "#DC2626",
        "warning":  "#D97706",
        "safe":     "#16A34A",
        "quiz":       "#7C3AED",
        "assignment": "#2563EB",
        "attendance": "#CA8A04",
        "open":       "#0D9488",
        "other":      "#57534E",
    },
    "rose_light": {
        "label": "Pastel Rose",
        "description": "Warm blush - soft rose",
        "mode": "light",
        "bg":             "#FFF5F6",
        "surface":        "#FFFFFF",
        "surface_hover":  "#FFF0F2",
        "accent":         "#DB2777",
        "text_primary":   "#4D0721",
        "text_secondary": "#9D174D",
        "border":         "#FCE7F3",
        "critical": "#E11D48",
        "warning":  "#EA580C",
        "safe":     "#059669",
        "quiz":       "#9333EA",
        "assignment": "#E11D48",
        "attendance": "#D97706",
        "open":       "#0D9488",
        "other":      "#78716C",
    },
}

THEME_ORDER = [
    "midnight_blue", "ocean_teal", "sakura_pink",
    "nord_frost", "monokai_pro", "solarized_dark",
    "steel_light", "rose_light",
]
